[package]
name = "lsi-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "CLI for LocalSend Improved"

[[bin]]
name = "localsend-improved"
path = "src/main.rs"

[dependencies]
lsi-core = { path = "../core" }
lsi-protocol-localsend-v2 = { path = "../protocol-localsend-v2" }
lsi-protocol-native-v1 = { path = "../protocol-native-v1" }
clap.workspace = true
anyhow.workspace = true
quinn.workspace = true
rustls.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true
