//! Stable hook event schema.

use serde::{Deserialize, Serialize};

/// Event emitted to configured hook sinks.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct HookEvent {
    /// Unique event id generated by the daemon.
    pub event_id: String,
    /// Stable event type.
    pub event_type: HookEventType,
    /// Unix timestamp in seconds.
    pub occurred_at_unix_seconds: i64,
    /// Event-specific JSON payload.
    pub payload: serde_json::Value,
}

/// Stable hook event type.
#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum HookEventType {
    /// Daemon startup completed.
    DaemonStarted,
    /// Transfer entered active state.
    TransferStarted,
    /// Transfer byte progress changed.
    TransferProgress,
    /// Transfer completed successfully.
    TransferCompleted,
    /// Transfer failed.
    TransferFailed,
    /// Inbox contents changed.
    InboxChanged,
    /// Peer was observed.
    PeerSeen,
}

impl HookEventType {
    /// Stable event type string.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::DaemonStarted => "daemon_started",
            Self::TransferStarted => "transfer_started",
            Self::TransferProgress => "transfer_progress",
            Self::TransferCompleted => "transfer_completed",
            Self::TransferFailed => "transfer_failed",
            Self::InboxChanged => "inbox_changed",
            Self::PeerSeen => "peer_seen",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn daemon_started_serializes_to_stable_json() {
        assert_event_json(
            HookEventType::DaemonStarted,
            serde_json::json!({ "alias": "server" }),
            r#"{"event_id":"event-1","event_type":"daemon_started","occurred_at_unix_seconds":42,"payload":{"alias":"server"}}"#,
        );
    }

    #[test]
    fn transfer_started_serializes_to_stable_json() {
        assert_event_json(
            HookEventType::TransferStarted,
            serde_json::json!({ "transfer_id": "transfer-1" }),
            r#"{"event_id":"event-1","event_type":"transfer_started","occurred_at_unix_seconds":42,"payload":{"transfer_id":"transfer-1"}}"#,
        );
    }

    #[test]
    fn transfer_completed_serializes_to_stable_json() {
        assert_event_json(
            HookEventType::TransferCompleted,
            serde_json::json!({ "transfer_id": "transfer-1" }),
            r#"{"event_id":"event-1","event_type":"transfer_completed","occurred_at_unix_seconds":42,"payload":{"transfer_id":"transfer-1"}}"#,
        );
    }

    #[test]
    fn transfer_progress_serializes_to_stable_json() {
        assert_event_json(
            HookEventType::TransferProgress,
            serde_json::json!({
                "bytes_done": 512,
                "bytes_total": 1024,
                "transfer_id": "transfer-1"
            }),
            r#"{"event_id":"event-1","event_type":"transfer_progress","occurred_at_unix_seconds":42,"payload":{"bytes_done":512,"bytes_total":1024,"transfer_id":"transfer-1"}}"#,
        );
    }

    #[test]
    fn transfer_failed_serializes_to_stable_json() {
        assert_event_json(
            HookEventType::TransferFailed,
            serde_json::json!({
                "code": "io",
                "message": "disk full",
                "transfer_id": "transfer-1"
            }),
            r#"{"event_id":"event-1","event_type":"transfer_failed","occurred_at_unix_seconds":42,"payload":{"code":"io","message":"disk full","transfer_id":"transfer-1"}}"#,
        );
    }

    #[test]
    fn inbox_changed_serializes_to_stable_json() {
        assert_event_json(
            HookEventType::InboxChanged,
            serde_json::json!({}),
            r#"{"event_id":"event-1","event_type":"inbox_changed","occurred_at_unix_seconds":42,"payload":{}}"#,
        );
    }

    #[test]
    fn peer_seen_serializes_to_stable_json() {
        assert_event_json(
            HookEventType::PeerSeen,
            serde_json::json!({
                "address": "127.0.0.1",
                "alias": "phone",
                "port": 53317
            }),
            r#"{"event_id":"event-1","event_type":"peer_seen","occurred_at_unix_seconds":42,"payload":{"address":"127.0.0.1","alias":"phone","port":53317}}"#,
        );
    }

    fn assert_event_json(event_type: HookEventType, payload: serde_json::Value, expected: &str) {
        let event = HookEvent {
            event_id: "event-1".to_string(),
            event_type,
            occurred_at_unix_seconds: 42,
            payload,
        };

        assert_eq!(serde_json::to_string(&event).unwrap(), expected);
    }
}
